server:
  port: 8764
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads 
spring: 
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://cxytiandi.com
        predicates:
        - Path=/course
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://yhl-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
