# sleuth配置
spring: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
  jackson:
    serialization:
      indent_output: false  
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://yhl-server:8761/eureka/
